// Generated by uniffi-bindgen-react-native
#include "lolistream-react-native-resvg.h"
#include "generated/rust.hpp"

namespace lolistream_reactnativeresvg {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRust::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}