// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "lolistream-react-native-resvg.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ResvgSpec.h"

@interface ReactNativeResvg : NSObject <NativeReactNativeResvgSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeResvg : NSObject <RCTBridgeModule>
#endif

@end